// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dashboarddata "github.com/tbe-team/raybot/internal/services/dashboarddata"
)

// FakeService is an autogenerated mock type for the Service type
type FakeService struct {
	mock.Mock
}

type FakeService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeService) EXPECT() *FakeService_Expecter {
	return &FakeService_Expecter{mock: &_m.Mock}
}

// GetRobotState provides a mock function with given fields: ctx
func (_m *FakeService) GetRobotState(ctx context.Context) (dashboarddata.RobotState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRobotState")
	}

	var r0 dashboarddata.RobotState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dashboarddata.RobotState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dashboarddata.RobotState); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dashboarddata.RobotState)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeService_GetRobotState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRobotState'
type FakeService_GetRobotState_Call struct {
	*mock.Call
}

// GetRobotState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FakeService_Expecter) GetRobotState(ctx interface{}) *FakeService_GetRobotState_Call {
	return &FakeService_GetRobotState_Call{Call: _e.mock.On("GetRobotState", ctx)}
}

func (_c *FakeService_GetRobotState_Call) Run(run func(ctx context.Context)) *FakeService_GetRobotState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FakeService_GetRobotState_Call) Return(_a0 dashboarddata.RobotState, _a1 error) *FakeService_GetRobotState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeService_GetRobotState_Call) RunAndReturn(run func(context.Context) (dashboarddata.RobotState, error)) *FakeService_GetRobotState_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeService creates a new instance of FakeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeService {
	mock := &FakeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
