// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/tbe-team/raybot/internal/storage/db"

	model "github.com/tbe-team/raybot/internal/model"

	paging "github.com/tbe-team/raybot/pkg/paging"

	sort "github.com/tbe-team/raybot/pkg/sort"
)

// FakeCommandRepository is an autogenerated mock type for the CommandRepository type
type FakeCommandRepository struct {
	mock.Mock
}

type FakeCommandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeCommandRepository) EXPECT() *FakeCommandRepository_Expecter {
	return &FakeCommandRepository_Expecter{mock: &_m.Mock}
}

// CreateCommand provides a mock function with given fields: ctx, _a1, command
func (_m *FakeCommandRepository) CreateCommand(ctx context.Context, _a1 db.SQLDB, command model.Command) error {
	ret := _m.Called(ctx, _a1, command)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB, model.Command) error); ok {
		r0 = rf(ctx, _a1, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeCommandRepository_CreateCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommand'
type FakeCommandRepository_CreateCommand_Call struct {
	*mock.Call
}

// CreateCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 db.SQLDB
//   - command model.Command
func (_e *FakeCommandRepository_Expecter) CreateCommand(ctx interface{}, _a1 interface{}, command interface{}) *FakeCommandRepository_CreateCommand_Call {
	return &FakeCommandRepository_CreateCommand_Call{Call: _e.mock.On("CreateCommand", ctx, _a1, command)}
}

func (_c *FakeCommandRepository_CreateCommand_Call) Run(run func(ctx context.Context, _a1 db.SQLDB, command model.Command)) *FakeCommandRepository_CreateCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SQLDB), args[2].(model.Command))
	})
	return _c
}

func (_c *FakeCommandRepository_CreateCommand_Call) Return(_a0 error) *FakeCommandRepository_CreateCommand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeCommandRepository_CreateCommand_Call) RunAndReturn(run func(context.Context, db.SQLDB, model.Command) error) *FakeCommandRepository_CreateCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommandByStatusInProgress provides a mock function with given fields: ctx, _a1
func (_m *FakeCommandRepository) GetCommandByStatusInProgress(ctx context.Context, _a1 db.SQLDB) (model.Command, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCommandByStatusInProgress")
	}

	var r0 model.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB) (model.Command, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB) model.Command); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Command)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLDB) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeCommandRepository_GetCommandByStatusInProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommandByStatusInProgress'
type FakeCommandRepository_GetCommandByStatusInProgress_Call struct {
	*mock.Call
}

// GetCommandByStatusInProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 db.SQLDB
func (_e *FakeCommandRepository_Expecter) GetCommandByStatusInProgress(ctx interface{}, _a1 interface{}) *FakeCommandRepository_GetCommandByStatusInProgress_Call {
	return &FakeCommandRepository_GetCommandByStatusInProgress_Call{Call: _e.mock.On("GetCommandByStatusInProgress", ctx, _a1)}
}

func (_c *FakeCommandRepository_GetCommandByStatusInProgress_Call) Run(run func(ctx context.Context, _a1 db.SQLDB)) *FakeCommandRepository_GetCommandByStatusInProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SQLDB))
	})
	return _c
}

func (_c *FakeCommandRepository_GetCommandByStatusInProgress_Call) Return(_a0 model.Command, _a1 error) *FakeCommandRepository_GetCommandByStatusInProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeCommandRepository_GetCommandByStatusInProgress_Call) RunAndReturn(run func(context.Context, db.SQLDB) (model.Command, error)) *FakeCommandRepository_GetCommandByStatusInProgress_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommands provides a mock function with given fields: ctx, _a1, params, sorts
func (_m *FakeCommandRepository) ListCommands(ctx context.Context, _a1 db.SQLDB, params paging.Params, sorts []sort.Sort) ([]model.Command, error) {
	ret := _m.Called(ctx, _a1, params, sorts)

	if len(ret) == 0 {
		panic("no return value specified for ListCommands")
	}

	var r0 []model.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB, paging.Params, []sort.Sort) ([]model.Command, error)); ok {
		return rf(ctx, _a1, params, sorts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB, paging.Params, []sort.Sort) []model.Command); ok {
		r0 = rf(ctx, _a1, params, sorts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLDB, paging.Params, []sort.Sort) error); ok {
		r1 = rf(ctx, _a1, params, sorts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeCommandRepository_ListCommands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommands'
type FakeCommandRepository_ListCommands_Call struct {
	*mock.Call
}

// ListCommands is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 db.SQLDB
//   - params paging.Params
//   - sorts []sort.Sort
func (_e *FakeCommandRepository_Expecter) ListCommands(ctx interface{}, _a1 interface{}, params interface{}, sorts interface{}) *FakeCommandRepository_ListCommands_Call {
	return &FakeCommandRepository_ListCommands_Call{Call: _e.mock.On("ListCommands", ctx, _a1, params, sorts)}
}

func (_c *FakeCommandRepository_ListCommands_Call) Run(run func(ctx context.Context, _a1 db.SQLDB, params paging.Params, sorts []sort.Sort)) *FakeCommandRepository_ListCommands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SQLDB), args[2].(paging.Params), args[3].([]sort.Sort))
	})
	return _c
}

func (_c *FakeCommandRepository_ListCommands_Call) Return(_a0 []model.Command, _a1 error) *FakeCommandRepository_ListCommands_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeCommandRepository_ListCommands_Call) RunAndReturn(run func(context.Context, db.SQLDB, paging.Params, []sort.Sort) ([]model.Command, error)) *FakeCommandRepository_ListCommands_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeCommandRepository creates a new instance of FakeCommandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeCommandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeCommandRepository {
	mock := &FakeCommandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
