// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/tbe-team/raybot/internal/storage/db"

	model "github.com/tbe-team/raybot/internal/model"
)

// FakeLocationRepository is an autogenerated mock type for the LocationRepository type
type FakeLocationRepository struct {
	mock.Mock
}

type FakeLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeLocationRepository) EXPECT() *FakeLocationRepository_Expecter {
	return &FakeLocationRepository_Expecter{mock: &_m.Mock}
}

// UpdateLocation provides a mock function with given fields: ctx, _a1, location
func (_m *FakeLocationRepository) UpdateLocation(ctx context.Context, _a1 db.SQLDB, location model.Location) error {
	ret := _m.Called(ctx, _a1, location)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLDB, model.Location) error); ok {
		r0 = rf(ctx, _a1, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeLocationRepository_UpdateLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLocation'
type FakeLocationRepository_UpdateLocation_Call struct {
	*mock.Call
}

// UpdateLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 db.SQLDB
//   - location model.Location
func (_e *FakeLocationRepository_Expecter) UpdateLocation(ctx interface{}, _a1 interface{}, location interface{}) *FakeLocationRepository_UpdateLocation_Call {
	return &FakeLocationRepository_UpdateLocation_Call{Call: _e.mock.On("UpdateLocation", ctx, _a1, location)}
}

func (_c *FakeLocationRepository_UpdateLocation_Call) Run(run func(ctx context.Context, _a1 db.SQLDB, location model.Location)) *FakeLocationRepository_UpdateLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SQLDB), args[2].(model.Location))
	})
	return _c
}

func (_c *FakeLocationRepository_UpdateLocation_Call) Return(_a0 error) *FakeLocationRepository_UpdateLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeLocationRepository_UpdateLocation_Call) RunAndReturn(run func(context.Context, db.SQLDB, model.Location) error) *FakeLocationRepository_UpdateLocation_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeLocationRepository creates a new instance of FakeLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeLocationRepository {
	mock := &FakeLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
