// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: location.sql

package sqlc

import (
	"context"
)

const locationGetCurrent = `-- name: LocationGetCurrent :one
SELECT id, current_location, updated_at FROM location
WHERE id = 1
`

func (q *Queries) LocationGetCurrent(ctx context.Context, db DBTX) (Location, error) {
	row := db.QueryRowContext(ctx, locationGetCurrent)
	var i Location
	err := row.Scan(&i.ID, &i.CurrentLocation, &i.UpdatedAt)
	return i, err
}

const locationUpdate = `-- name: LocationUpdate :exec
UPDATE location
SET
	current_location = ?,
	updated_at = ?
WHERE id = 1
`

type LocationUpdateParams struct {
	CurrentLocation string `json:"current_location"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) LocationUpdate(ctx context.Context, db DBTX, arg LocationUpdateParams) error {
	_, err := db.ExecContext(ctx, locationUpdate, arg.CurrentLocation, arg.UpdatedAt)
	return err
}
