// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: location.sql

package sqlc

import (
	"context"
	"time"
)

const locationUpdate = `-- name: LocationUpdate :exec
UPDATE location
SET
	current_location = ?,
	updated_at = ?
WHERE id = 1
`

type LocationUpdateParams struct {
	CurrentLocation string    `json:"current_location"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) LocationUpdate(ctx context.Context, db DBTX, arg LocationUpdateParams) error {
	_, err := db.ExecContext(ctx, locationUpdate, arg.CurrentLocation, arg.UpdatedAt)
	return err
}
