// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type RobotState struct {
	BatteryState        string `json:"battery_state"`
	ChargeState         string `json:"charge_state"`
	DischargeState      string `json:"discharge_state"`
	DistanceSensorState string `json:"distance_sensor_state"`
	LiftMotorState      string `json:"lift_motor_state"`
	DriveMotorState     string `json:"drive_motor_state"`
}
