// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: robot_state.sql

package sqlc

import (
	"context"
)

const robotStateGet = `-- name: RobotStateGet :one
SELECT battery_state, charge_state, discharge_state, distance_sensor_state, lift_motor_state, drive_motor_state, location_state FROM robot_state LIMIT 1
`

func (q *Queries) RobotStateGet(ctx context.Context, db DBTX) (RobotState, error) {
	row := db.QueryRowContext(ctx, robotStateGet)
	var i RobotState
	err := row.Scan(
		&i.BatteryState,
		&i.ChargeState,
		&i.DischargeState,
		&i.DistanceSensorState,
		&i.LiftMotorState,
		&i.DriveMotorState,
		&i.LocationState,
	)
	return i, err
}

const robotStateUpdate = `-- name: RobotStateUpdate :exec
UPDATE robot_state
SET
	battery_state = ?,
	charge_state = ?,
	discharge_state = ?,
	distance_sensor_state = ?,
	lift_motor_state = ?,
	drive_motor_state = ?,
	location_state = ?
`

type RobotStateUpdateParams struct {
	BatteryState        string `json:"battery_state"`
	ChargeState         string `json:"charge_state"`
	DischargeState      string `json:"discharge_state"`
	DistanceSensorState string `json:"distance_sensor_state"`
	LiftMotorState      string `json:"lift_motor_state"`
	DriveMotorState     string `json:"drive_motor_state"`
	LocationState       string `json:"location_state"`
}

func (q *Queries) RobotStateUpdate(ctx context.Context, db DBTX, arg RobotStateUpdateParams) error {
	_, err := db.ExecContext(ctx, robotStateUpdate,
		arg.BatteryState,
		arg.ChargeState,
		arg.DischargeState,
		arg.DistanceSensorState,
		arg.LiftMotorState,
		arg.DriveMotorState,
		arg.LocationState,
	)
	return err
}
