// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/tbe-team/raybot/internal/services/command"

	mock "github.com/stretchr/testify/mock"
)

// FakeExecutorService is an autogenerated mock type for the ExecutorService type
type FakeExecutorService struct {
	mock.Mock
}

type FakeExecutorService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeExecutorService) EXPECT() *FakeExecutorService_Expecter {
	return &FakeExecutorService_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *FakeExecutorService) Execute(ctx context.Context, cmd command.Command) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Command) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeExecutorService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FakeExecutorService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.Command
func (_e *FakeExecutorService_Expecter) Execute(ctx interface{}, cmd interface{}) *FakeExecutorService_Execute_Call {
	return &FakeExecutorService_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *FakeExecutorService_Execute_Call) Run(run func(ctx context.Context, cmd command.Command)) *FakeExecutorService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.Command))
	})
	return _c
}

func (_c *FakeExecutorService_Execute_Call) Return(_a0 error) *FakeExecutorService_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeExecutorService_Execute_Call) RunAndReturn(run func(context.Context, command.Command) error) *FakeExecutorService_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeExecutorService creates a new instance of FakeExecutorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeExecutorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeExecutorService {
	mock := &FakeExecutorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
