// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/tbe-team/raybot/internal/service"
)

// FakePICService is an autogenerated mock type for the PICService type
type FakePICService struct {
	mock.Mock
}

type FakePICService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakePICService) EXPECT() *FakePICService_Expecter {
	return &FakePICService_Expecter{mock: &_m.Mock}
}

// ProcessSerialCommandACK provides a mock function with given fields: ctx, params
func (_m *FakePICService) ProcessSerialCommandACK(ctx context.Context, params service.ProcessSerialCommandACK) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ProcessSerialCommandACK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ProcessSerialCommandACK) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakePICService_ProcessSerialCommandACK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessSerialCommandACK'
type FakePICService_ProcessSerialCommandACK_Call struct {
	*mock.Call
}

// ProcessSerialCommandACK is a helper method to define mock.On call
//   - ctx context.Context
//   - params service.ProcessSerialCommandACK
func (_e *FakePICService_Expecter) ProcessSerialCommandACK(ctx interface{}, params interface{}) *FakePICService_ProcessSerialCommandACK_Call {
	return &FakePICService_ProcessSerialCommandACK_Call{Call: _e.mock.On("ProcessSerialCommandACK", ctx, params)}
}

func (_c *FakePICService_ProcessSerialCommandACK_Call) Run(run func(ctx context.Context, params service.ProcessSerialCommandACK)) *FakePICService_ProcessSerialCommandACK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.ProcessSerialCommandACK))
	})
	return _c
}

func (_c *FakePICService_ProcessSerialCommandACK_Call) Return(_a0 error) *FakePICService_ProcessSerialCommandACK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakePICService_ProcessSerialCommandACK_Call) RunAndReturn(run func(context.Context, service.ProcessSerialCommandACK) error) *FakePICService_ProcessSerialCommandACK_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakePICService creates a new instance of FakePICService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakePICService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakePICService {
	mock := &FakePICService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
