// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/tbe-team/raybot/internal/model"

	service "github.com/tbe-team/raybot/internal/service"
)

// FakeRobotService is an autogenerated mock type for the RobotService type
type FakeRobotService struct {
	mock.Mock
}

type FakeRobotService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeRobotService) EXPECT() *FakeRobotService_Expecter {
	return &FakeRobotService_Expecter{mock: &_m.Mock}
}

// GetRobotState provides a mock function with given fields: ctx
func (_m *FakeRobotService) GetRobotState(ctx context.Context) (model.RobotState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRobotState")
	}

	var r0 model.RobotState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.RobotState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.RobotState); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.RobotState)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeRobotService_GetRobotState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRobotState'
type FakeRobotService_GetRobotState_Call struct {
	*mock.Call
}

// GetRobotState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FakeRobotService_Expecter) GetRobotState(ctx interface{}) *FakeRobotService_GetRobotState_Call {
	return &FakeRobotService_GetRobotState_Call{Call: _e.mock.On("GetRobotState", ctx)}
}

func (_c *FakeRobotService_GetRobotState_Call) Run(run func(ctx context.Context)) *FakeRobotService_GetRobotState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FakeRobotService_GetRobotState_Call) Return(_a0 model.RobotState, _a1 error) *FakeRobotService_GetRobotState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeRobotService_GetRobotState_Call) RunAndReturn(run func(context.Context) (model.RobotState, error)) *FakeRobotService_GetRobotState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRobotState provides a mock function with given fields: ctx, params
func (_m *FakeRobotService) UpdateRobotState(ctx context.Context, params service.UpdateRobotStateParams) (model.RobotState, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRobotState")
	}

	var r0 model.RobotState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UpdateRobotStateParams) (model.RobotState, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UpdateRobotStateParams) model.RobotState); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(model.RobotState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UpdateRobotStateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeRobotService_UpdateRobotState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRobotState'
type FakeRobotService_UpdateRobotState_Call struct {
	*mock.Call
}

// UpdateRobotState is a helper method to define mock.On call
//   - ctx context.Context
//   - params service.UpdateRobotStateParams
func (_e *FakeRobotService_Expecter) UpdateRobotState(ctx interface{}, params interface{}) *FakeRobotService_UpdateRobotState_Call {
	return &FakeRobotService_UpdateRobotState_Call{Call: _e.mock.On("UpdateRobotState", ctx, params)}
}

func (_c *FakeRobotService_UpdateRobotState_Call) Run(run func(ctx context.Context, params service.UpdateRobotStateParams)) *FakeRobotService_UpdateRobotState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.UpdateRobotStateParams))
	})
	return _c
}

func (_c *FakeRobotService_UpdateRobotState_Call) Return(_a0 model.RobotState, _a1 error) *FakeRobotService_UpdateRobotState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeRobotService_UpdateRobotState_Call) RunAndReturn(run func(context.Context, service.UpdateRobotStateParams) (model.RobotState, error)) *FakeRobotService_UpdateRobotState_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeRobotService creates a new instance of FakeRobotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeRobotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeRobotService {
	mock := &FakeRobotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
