// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	peripheral "github.com/tbe-team/raybot/internal/services/peripheral"
)

// FakeService is an autogenerated mock type for the Service type
type FakeService struct {
	mock.Mock
}

type FakeService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeService) EXPECT() *FakeService_Expecter {
	return &FakeService_Expecter{mock: &_m.Mock}
}

// ListAvailableSerialPorts provides a mock function with given fields: ctx
func (_m *FakeService) ListAvailableSerialPorts(ctx context.Context) ([]peripheral.SerialPort, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableSerialPorts")
	}

	var r0 []peripheral.SerialPort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]peripheral.SerialPort, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []peripheral.SerialPort); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]peripheral.SerialPort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeService_ListAvailableSerialPorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailableSerialPorts'
type FakeService_ListAvailableSerialPorts_Call struct {
	*mock.Call
}

// ListAvailableSerialPorts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FakeService_Expecter) ListAvailableSerialPorts(ctx interface{}) *FakeService_ListAvailableSerialPorts_Call {
	return &FakeService_ListAvailableSerialPorts_Call{Call: _e.mock.On("ListAvailableSerialPorts", ctx)}
}

func (_c *FakeService_ListAvailableSerialPorts_Call) Run(run func(ctx context.Context)) *FakeService_ListAvailableSerialPorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FakeService_ListAvailableSerialPorts_Call) Return(_a0 []peripheral.SerialPort, _a1 error) *FakeService_ListAvailableSerialPorts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeService_ListAvailableSerialPorts_Call) RunAndReturn(run func(context.Context) ([]peripheral.SerialPort, error)) *FakeService_ListAvailableSerialPorts_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeService creates a new instance of FakeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeService {
	mock := &FakeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
