// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	limitswitch "github.com/tbe-team/raybot/internal/services/limitswitch"
)

// FakeService is an autogenerated mock type for the Service type
type FakeService struct {
	mock.Mock
}

type FakeService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeService) EXPECT() *FakeService_Expecter {
	return &FakeService_Expecter{mock: &_m.Mock}
}

// GetLimitSwitchState provides a mock function with given fields: ctx
func (_m *FakeService) GetLimitSwitchState(ctx context.Context) (limitswitch.GetLimitSwitchStateOutput, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitSwitchState")
	}

	var r0 limitswitch.GetLimitSwitchStateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (limitswitch.GetLimitSwitchStateOutput, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) limitswitch.GetLimitSwitchStateOutput); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(limitswitch.GetLimitSwitchStateOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeService_GetLimitSwitchState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitSwitchState'
type FakeService_GetLimitSwitchState_Call struct {
	*mock.Call
}

// GetLimitSwitchState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FakeService_Expecter) GetLimitSwitchState(ctx interface{}) *FakeService_GetLimitSwitchState_Call {
	return &FakeService_GetLimitSwitchState_Call{Call: _e.mock.On("GetLimitSwitchState", ctx)}
}

func (_c *FakeService_GetLimitSwitchState_Call) Run(run func(ctx context.Context)) *FakeService_GetLimitSwitchState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FakeService_GetLimitSwitchState_Call) Return(_a0 limitswitch.GetLimitSwitchStateOutput, _a1 error) *FakeService_GetLimitSwitchState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeService_GetLimitSwitchState_Call) RunAndReturn(run func(context.Context) (limitswitch.GetLimitSwitchStateOutput, error)) *FakeService_GetLimitSwitchState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLimitSwitchByID provides a mock function with given fields: ctx, params
func (_m *FakeService) UpdateLimitSwitchByID(ctx context.Context, params limitswitch.UpdateLimitSwitchByIDParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLimitSwitchByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, limitswitch.UpdateLimitSwitchByIDParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeService_UpdateLimitSwitchByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLimitSwitchByID'
type FakeService_UpdateLimitSwitchByID_Call struct {
	*mock.Call
}

// UpdateLimitSwitchByID is a helper method to define mock.On call
//   - ctx context.Context
//   - params limitswitch.UpdateLimitSwitchByIDParams
func (_e *FakeService_Expecter) UpdateLimitSwitchByID(ctx interface{}, params interface{}) *FakeService_UpdateLimitSwitchByID_Call {
	return &FakeService_UpdateLimitSwitchByID_Call{Call: _e.mock.On("UpdateLimitSwitchByID", ctx, params)}
}

func (_c *FakeService_UpdateLimitSwitchByID_Call) Run(run func(ctx context.Context, params limitswitch.UpdateLimitSwitchByIDParams)) *FakeService_UpdateLimitSwitchByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(limitswitch.UpdateLimitSwitchByIDParams))
	})
	return _c
}

func (_c *FakeService_UpdateLimitSwitchByID_Call) Return(_a0 error) *FakeService_UpdateLimitSwitchByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeService_UpdateLimitSwitchByID_Call) RunAndReturn(run func(context.Context, limitswitch.UpdateLimitSwitchByIDParams) error) *FakeService_UpdateLimitSwitchByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeService creates a new instance of FakeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeService {
	mock := &FakeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
